### ISSUE TITLE
undefined method `path_for' for #<ActiveStorage::Service::PostgreSQLService>

### ISSUE THREAD

**Issue by tkoenig** [lsylvester/active_storage-postgresql#5]
Hi,

I'm trying to get this to work on a new rails 5.2.2 application.

But whenever I try to render an item in a view I get the following error:

```
undefined method `path_for' for #<ActiveStorage::Service::PostgreSQLService:0x00007fa44dbf8378>
```

```
activestorage (5.2.2) app/controllers/active_storage/disk_controller.rb:12:in `show'
actionpack (5.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.2) lib/abstract_controller/base.rb:194:in `process_action'
....
```
I guess this comes from calling the `url_helpers.rails_disk_service_url` helpers...

Any idea on how to fix this issue?

**Comment by lsylvester** [comment]
Hi @tkoenig, 

Thanks for your issue report. I have confirmed that this is an issue, and have made a fix for it in master.
