### PR TITLE
Postgresql controller

### LINKED ISSUE #5: undefined method `path_for' for #<ActiveStorage::Service::PostgreSQLService>
Hi,

I'm trying to get this to work on a new rails 5.2.2 application.

But whenever I try to render an item in a view I get the following error:

```
undefined method `path_for' for #<ActiveStorage::Service::PostgreSQLService:0x00007fa44dbf8378>
```

```
activestorage (5.2.2) app/controllers/active_storage/disk_controller.rb:12:in `show'
actionpack (5.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.2) lib/abstract_controller/base.rb:194:in `process_action'
....
```
I guess this comes from calling the `url_helpers.rails_disk_service_url` helpers...

Any idea on how to fix this issue?

### PR DESCRIPTION
**Pull request by lsylvester**
In rails/rails@390097531bd17369f05a23eba58c37b850ac95dd, the `ActiveStorage::DiskController` started to use apis on the `DiskService` that were not part of the standard service interface.

As a result, the `ActiveStorage::DiskController`  is no longer able to service files from the `PostgreSQL` backend.

This PR makes a new dedicated controller for serving PostgreSQL files, and implements support for `Range` heads which were added to the  `ActiveStorage::DiskController`.

This makes `active_storage-postgresql` compatible with Rails 5.2.2.

Fixes #5

### CODE REVIEW

**Comment by ajesler** [comment]
Thanks for fixing this @lsylvester. Would you be able to release a new gem version with this fix in it? Is there anything I can do to help get that done?

**Comment by DatabloxInt** [comment]
Thank you for taking the time to fix this, do you have an inkling as to when them gem will be released?
Steven

**Comment by lsylvester** [comment]
@ajesler @DatabloxInt I have published a new version of the gem with this fix in it.
